SET IDENTITY_INSERT [dbo].[Companies] ON
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (1, N'Minnesota Mining & Manufacturing', N'3M')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (2, N'American Family Life Assurance Company', N'AFLAC')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (3, N'Aluminum Company of America', N'Alcoa')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (4, N'Applied Molecular Genetics', N'Amgen')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (5, N'American Oil Company', N'Amoco')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (6, N'American Telephone and Telegraph', N'AT&T')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (7, N'Continental Oil Company', N'Conoco')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (8, N'Federal Express (courier company)', N'FedEx')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (9, N'Fabbrica Italiana Automobili Torino', N'Fiat')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (10, N'Dalsey, Hillblom and Lynn (courier company)', N'DHL')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (11, N'Bayerische Motoren Werke', N'BMW')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (12, N'Pacific Gas and Electric Company', N'PG&E')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (13, N'United Bank of Switzerland', N'UBS')
INSERT INTO [dbo].[Companies] ([Id], [Name], [Abbreviation]) VALUES (14, N'Volkswagen', N'VW')
SET IDENTITY_INSERT [dbo].[Companies] OFF
